#!/bin/bash
source helper

git clone https://github.com/actionml/universal-recommender.git ./other-engines/ur

cp ./other-engines/customize/ur/data/* ./other-engines/ur/data/
cp ./other-engines/customize/ur/example/* ./other-engines/ur/examples

docker build --pull --build-arg http_proxy="$http_proxy" --build-arg https_proxy="$https_proxy" $@ -t ${IMAGE} .

