#!/usr/bin/env bash

# exit on any error
set -e

echo ""
echo "NLT test for The Universal Recommender."
echo "If some step fails check that your engine.json file has been restored"
echo "or look for it in 'user-engine.json'"
echo ""

echo "Checking for needed files"
if [ ! -f examples/nlt-engine.json ]; then
    echo "File not found: examples/nlt-engine.json"
    exit 1
fi

if [ ! -f data/nlt-data.txt ]; then
    echo "File not found: data/nlt-data.txt"
    exit 1
fi

if [ -f user-engine.json ]; then
    echo "File user-engine.json found, this may be an error so we cannot replace engine.json"
    exit 1
fi


echo ""
echo "Checking status, should exit if pio is not running."
pio status
pio app new nlt || true

echo ""
echo "Checking to see if nlt app exists, should exit if not."
pio app show nlt

echo ""
echo "Moving engine.json to user-engine.json if it exists"
cp -n engine.json user-engine.json || true

echo ""
echo "Moving examples/nlt-engine.json to engine.json for nlt test."
cp examples/nlt-engine.json engine.json

echo ""
echo "Deleting nlt app data since the test is date dependent"
pio app data-delete nlt -f

echo ""
echo "Importing data for nlt test"
# get the access_key from pio app list
ACCESS_KEY=`pio app show nlt | grep Key | cut -f 7 -d ' '`
echo -n "Access key: "
echo $ACCESS_KEY
python3 examples/import_nlt.py --access_key $ACCESS_KEY --file data/nlt-data.txt

echo ""
echo "Building and delpoying model"
pio build --clean
pio train  -- --driver-memory 4g --executor-memory 4g
echo "-----------------------"
echo "Done!"
echo "-----------------------"